### ISSUE TITLE
Missing log.js

### ISSUE THREAD

**Issue by Brummolix** [protz/thunderbird-stdlib#16]
The File misc.js is including "../log.js"
( via `XPCOMUtils.importRelative(this, "../log.js");` )

Where do I get this log.js from?

**Comment by Standard8** [comment]
Log.js would be something based on the one for thunderbird-conversations: https://github.com/protz/thunderbird-conversations/blob/master/modules/log.js

**Comment by Standard8** [comment]
No follow-ups, so closing for now.
